apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-membership
  labels:
    app: gym-membership
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gym-membership
  template:
    metadata:
      labels:
        app: gym-membership
    spec:
      containers:
      - name: gym-membership
        image: app:v2.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
